main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
	path('', views.IndexView.as_view(), name="home"),
	path('contact/', views.ContactView.as_view(), name="contact"),
	path('portfolio/', views.PortfolioView.as_view(), name="portfolios"),
	path('portfolio/<slug:slug>', views.PortfolioDetailView.as_view(), name="portfolio"),
	path('blog/', views.BlogView.as_view(), name="blogs"),
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"),
	]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Skill(models.Model):
    class Meta:
        verbose_name_plural = 'Skills'
        verbose_name = 'Skill'
    
    name = models.CharField(max_length=20, blank=True, null=True)
    score = models.IntegerField(default=80, blank=True, null=True)
    image = models.FileField(blank=True, null=True, upload_to="skills")
    is_key_skill = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

class UserProfile(models.Model):

    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name = 'User Profile'
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
    title = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    skills = models.ManyToManyField(Skill, blank=True)
    cv = models.FileField(blank=True, null=True, upload_to="cv")

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class ContactProfile(models.Model):
    
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]
    timestamp = models.DateTimeField(auto_now_add=True)
    name = models.CharField(verbose_name="Name",max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Message")

    def __str__(self):
        return f'{self.name}'



class Testimonial(models.Model):

    class Meta:
        verbose_name_plural = 'Testimonials'
        verbose_name = 'Testimonial'
        ordering = ["name"]

    thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
    name = models.CharField(max_length=200, blank=True, null=True)
    role = models.CharField(max_length=200, blank=True, null=True)
    quote = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Media(models.Model):

    class Meta:
        verbose_name_plural = 'Media Files'
        verbose_name = 'Media'
        ordering = ["name"]
	
    image = models.ImageField(blank=True, null=True, upload_to="media")
    url = models.URLField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    is_image = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.url:
            self.is_image = False
        super(Media, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Portfolio(models.Model):

    class Meta:
        verbose_name_plural = 'Portfolio Profiles'
        verbose_name = 'Portfolio'
        ordering = ["name"]
    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to="portfolio")
    slug = models.SlugField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Portfolio, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/portfolio/{self.slug}"


class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"


class Certificate(models.Model):

    class Meta:
        verbose_name_plural = 'Certificates'
        verbose_name = 'Certificate'

    date = models.DateTimeField(blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			'class': 'form-control'
			}))
	email = forms.EmailField(max_length=254, required=True, 
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			'class': 'form-control'
			}))
	message = forms.CharField(max_length=1000, required=True, 
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'class': 'form-control',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

main/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import (
		UserProfile,
		Blog,
		Portfolio,
		Testimonial,
		Certificate
	)

from django.views import generic


from . forms import ContactForm


class IndexView(generic.TemplateView):
	template_name = "main/index.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		testimonials = Testimonial.objects.filter(is_active=True)
		certificates = Certificate.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		portfolio = Portfolio.objects.filter(is_active=True)
		
		context["testimonials"] = testimonials
		context["certificates"] = certificates
		context["blogs"] = blogs
		context["portfolio"] = portfolio
		return context


class ContactView(generic.FormView):
	template_name = "main/contact.html"
	form_class = ContactForm
	success_url = "/"
	
	def form_valid(self, form):
		form.save()
		messages.success(self.request, 'Thank you. We will be in touch soon.')
		return super().form_valid(form)


class PortfolioView(generic.ListView):
	model = Portfolio
	template_name = "main/portfolio.html"
	paginate_by = 10

	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class PortfolioDetailView(generic.DetailView):
	model = Portfolio
	template_name = "main/portfolio-detail.html"

class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}cynthia{%endblock %}</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <link rel="canonical" href="{{request.path}}"/>
        <link rel="home" href="{% url 'main:home' %}"/>    
        <meta name="description" content="{% block description %}{% endblock %}">
        <meta name="keywords" content="{% block keywords %}{% endblock %}">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body data-spy="scroll" data-target=".navbar" data-offset="51">
        {% include 'main/partials/messages.html' %}
        {% include 'main/partials/nav.html' %}

        {% block content %}{% endblock %}

        {% include 'main/partials/footer.html' %}

        
        <!-- Back to top button -->
        <a href="#" class="btn back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        
        <!-- Pre Loader -->
        <div id="loader" class="show">
            <div class="loader"></div>
        </div>

        
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/wow/wow.min.js' %}"></script>
        <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
        <script src="{% static 'lib/typed/typed.min.js' %}"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
        
        <!-- Contact Javascript File -->
        <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
        <script src="{% static 'mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

main/templates/main/blog-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<div class="blog" id="blog">
    <div class="container">
        <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
            <h2>{{object.name|title}}</h2>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="blog-item wow fadeInUp" data-wow-delay="0.1s">
                    {% for obj in object_list %}
                    <h4 class="smTitle pb-3">{{object.author|title}}</h4>
                    <div class="col-md">
                        <h4 class="smTitle pb-3">{{object.timestamp.date}}</h4>
                      </div>
                      <div class="container">
                        {{object.body|safe}}
                      </div>
                    {% endfor %}
                </div>
            </div>
           
        </div>
    </div>
</div>
{%endblock%}
<!-- Blog End -->

main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Cynthia Aoko - home{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->
<!-- Blog Start -->
{% block content %}
<div class="blog" id="blog">
    <div class="container">
        <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
            <h2>Latest blogs</h2>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="blog-item wow fadeInUp" data-wow-delay="0.1s">
                    {% for obj in object_list %}
                    <a href="{% url 'main:blog' slug=obj.slug %}" ></a>
                    <div class="blog-img">
                        <img src="{{obj.image.url}}" alt="Blog">
                    </div>
                    {% endfor %}
                </div>
            </div>
           
        </div>
    </div>
</div>
{%endblock%}
<!-- Blog End -->

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Cynthia Aoko - contact{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->
 <!-- Contact Start -->
 {% block content %}
 <div class="contact wow fadeInUp" data-wow-delay="0.1s" id="contact">
    <div class="container-fluid">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-4"></div>
                <div class="col-md-8">
                    <div class="contact-form">
                        <div id="success"></div>
                        <form id="contactForm" method="POST" action="/contact/" novalidate="novalidate">
                            {% csrf_token %}
                            <label for="name">Name</label>
                            {{form.name}}

                            <label for="email">Email</label>
                            {{form.email}}

                            <label for="subject">Message</label>
                            {{form.message}}

                            <input class="btn" type="submit" value="Submit">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->
<!-- Contact End -->
{%endblock%}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Cynthia Aoko - home{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->
<!-- start content -->

{% block content %}
    <!-- Hero Start -->
    <div class="hero" id="home">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-sm-12 col-md-6">
                        <div class="hero-content">
                            <div class="hero-text">
                                <h1 class="xlTitle pb-3">Hi, I’m {{me.first_name|title}},  </h1>
                                <h2></h2>
                                <div class="typed-text">a {{me.userprofile.title}}</div>
                                <p>{{me.userprofile.bio}}</p>
                            </div>
                            <div class="hero-btn">
                                <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                                <a href="{% url 'main:contact' %}" class="btn btnOutline">Contact</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 d-none d-md-block">
                        <div class="hero-image">
                            <img src="{{me.userprofile.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <!-- Hero End -->

        <!-- skill Start -->
        <div class="about wow fadeInUp" data-wow-delay="0.1s" id="about">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <div class="about-content">
                            <div class="section-header text-left">
                                <p>Learn About Me</p> 
                                <h4 class="smTitle pb-3">Key Skills</h4>
                                {% for sk in me.userprofile.skills.all %}
                                {% if sk.is_key_skill %}
                            </div>
                            
                            <div class="skills">
                                {% if sk.image %}
                                <div class="skill-name">
                                    <div class="ksIconCol">
                                        <img src="{{sk.image.url}}" alt="...">
                                      </div>
                                      {% endif %}
                                    <span class="skill-Text">{{sk.name}}</span>
                                </div>
                                {% endif %}
                                {% endfor %}
                                
                            </div>
                            <a class="btn" href="">Learn More</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-content">
                            <div class="section-header text-left">
                                <h4 class="smTitle pb-3">Coding Skills</h4>
                                {% for sk in me.userprofile.skills.all %}
                                {% if not sk.is_key_skill %}
                            </div>
                            <div class="skills">
                                <div class="skill-name">
                                    <p>{{sk.name}}</p><p>{{sk.score}}</p>
                                </div>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar"style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                            <a class="btn" href="">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- skill End -->
         
        <!-- Certificate Start -->
        <!-- <div class="service" id="service">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>Certificates</p>
                </div>
                <div class="row">
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.0s">
                        <div class="service-item">
                            <div class="service-icon">
                                <i class="fa fa-laptop"></i>
                            </div>
                            {% for c in certificates %}
                            {% if c.is_active %}
                            <div class="service-text">
                                <a href="javascript:void(0)">{{c.title}}</a>
                                <ul class="cardOptionCol">
                                    <h6>{{c.date.date}}</h6>
                                    <h6>{{c.name|title}}</h6>
                                <p>{{c.description}}</p>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div> -->
        <!-- certificate End -->
        
        <!-- Portfolio Start -->
        <!-- <div class="portfolio" id="portfolio">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>Featured work</p>
                </div>
                <div class="col-auto">
                    <a href="{% url 'main:portfolios' %}" class="btn btnPrimary">View all</a>
                  </div>
                  {% for p in portfolio %}
                  {% if p.is_active %}
                <div class="row portfolio-container">
                    <div class="col-lg-4 col-md-6 col-sm-12 portfolio-item filter-1 wow fadeInUp" data-wow-delay="0.0s">
                        <div class="portfolio-wrap">
                            <div class="portfolio-img">
                                <img src="{% url 'main:portfolio' slug=p.slug %}"  src="{{p.image.url}}" alt="Image">
                            </div>
                            
                            <div class="portfolio-text">
                                <h3>{{p.name}}</h3>
                                <a class="btn" href="{% url 'main:portfolio' slug=p.slug %}" data-lightbox="portfolio">+</a>
                                <h3>{{p.date.year}}</h3>
                                <p>{{p.description}}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div> -->
        <!-- Portfolio End -->
        
        <!-- Testimonial Start -->
        <div class="testimonial wow fadeInUp" data-wow-delay="0.1s" id="review">
            <div class="container">
                <div class="testimonial-icon">
                    <i class="fa fa-quote-left"></i>
                </div>
                <div class="owl-carousel testimonials-carousel">
                    {% for t in testimonials %}
                    {% if t.is_active %}
                    <div class="testimonial-item">
                        <div class="testimonial-img">
                            <img src="{{t.thumbnail.url}}" alt="Image">
                        </div>
                        <div class="testimonial-text">
                            <p>{{t.quote}}</p>
                            <h3>{{t.name}}</h3>
                            <h4>{{t.role}}</h4>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Testimonial End -->

        <!-- Blog Start -->
        <!-- <div class="blog" id="blog">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>From Blog</p>
                    <h2>Latest Articles</h2>
                </div>
                <div class="col-auto">
                    <a href="{% url 'main:blogs' %}" class="btn">View all</a>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        {% for b in blogs %}
                        {% if b.is_active %}
                        <div class="blog-item wow fadeInUp" data-wow-delay="0.1s">
                            <div class="blog-img">
                                <img src="{% url 'main:blog' slug=b.slug %}" alt="Blog">
                            </div>
                            <div class="blog-text">
                                <h2>{{b.name}}</h2>
                                <div class="blog-meta">
                                    <p><i class="far fa-user"></i>{{b.author}}</p>
                                    <p><i class="far fa-list-alt"></i>{{b.name}}</p>
                                    <p><i class="far fa-calendar-alt"></i>{{b.timestamp.date}}</p>
                                    
                                </div>
                                <p>{{b.description}}</p>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    
                </div>
            </div>
        </div> -->
        <!-- Blog End -->
        {% endblock %}
        <!-- end content  -->

main/templates/main/partials/footer.html
{% load static %}

        <!-- Footer Start -->
        <div class="footer wow fadeIn" data-wow-delay="0.3s">
            <div class="container-fluid">
                <div class="container">
                    <div class="footer-info">
                        <h2>Cynthia Aoko</h2>
                       
                        <div class="footer-social">
                            <!-- <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a> -->
                        </div>
                    </div>
                </div>
                <div class="container copyright">
                    <p>Copyright ©{% now 'Y' %} All rights reserved. Cynthia Aoko</p>
                </div>
            </div>
        </div>
        <!-- Footer End -->

main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

main/templates/main/partials/nav.html
{% load static %}

<!-- Nav Bar Start -->
<div class="navbar navbar-expand-lg bg-light navbar-light">
    <div class="container-fluid">
        <a href="{% url 'main:home' %}" class="navbar-brand">Cynthia</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav ml-auto">
                <a href="{% url 'main:home' %}" class="nav-item nav-link active">Home</a>
                <!-- <a href="{%url 'main:portfolios' %}" class="nav-item nav-link">Portfolio</a> -->
                <!-- <a href="{% url 'main:blogs' %}" class="nav-item nav-link">Blog</a> -->
                <a href="{%url 'main:contact'%}" class="nav-item nav-link">Contact</a>
            </div>
        </div>
    </div>
</div>
<!-- Nav Bar End -->

main/templates/main/portfolio.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Cynthia Aoko - home{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->
<!-- Portfolio Start -->
{% block content %}
 <div class="portfolio" id="portfolio">
    <div class="container">
        <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
            <p>See my recent projects below</p>
        </div>
        <div class="row portfolio-container">
            <div class="col-lg-4 col-md-6 col-sm-12 portfolio-item filter-1 wow fadeInUp" data-wow-delay="0.0s">
                {% for obj in object_list %}
                <div class="portfolio-wrap">
                    <div class="portfolio-img">
                        <img src="{{obj.image.url}}" alt="Image">
                    </div>
                    
                    <div class="portfolio-text">
                        <a class="btn" href="{% url 'main:portfolio' slug=obj.slug %}"data-lightbox="portfolio">+</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}
<!-- Portfolio End -->